### PR TITLE
Added a separator setting to filters.stringfilter.StringSubstitutionFilter

### PR DESCRIPTION
**Pull request by fsteggink**
I had a use case where I would like to substitute a template string with Windows paths. They contain a colon, but since this was also used as the separator character, I could not substitute my data properly. So in this PR I've introduced a new setting to StringSubstitutionFilter, so a separator can be defined.

### CODE REVIEW

**Comment by justb4** [comment]
Ok, makes sense, only the nasty flake8 error to be fixed:

```
$ flake8
./stetl/filters/stringfilter.py:49:1: W293 blank line contains whitespace

```

**Comment by fsteggink** [comment]
Yeah, I just noticed this ;)

**Comment by fsteggink** [comment]
OK, zal ik doen. Ik heb gewoon de werkwijze van self.format_args daarboven gevolgd.

**Comment by fsteggink** [comment]
Beide settigns zijn aangepast.

**Comment by justb4** [comment]
Thanks for patience!

**Pull request merged**
