### PR TITLE
Ogroutput always apply lco, fixes #84

### LINKED ISSUE #84: Add option to always apply LCO
When using a ZIP file as input (for example the dutch dataset Bestuurlijke Grenzen, which is a ZIP file containing GML files), the layer creation options are only applied for the first GML file in this ZIP file.

I've made a patch with an option, named always_apply_lco, added to OgrOutput and Ogr2OgrExecOutput. When this option is set to true, the LCO's are always added to the ogr2ogr command string. I will create a PR when the Python 3 migration is done.

### PR DESCRIPTION
**Pull request by fsteggink**
For some reason I've never sent a PR for this and other fixes, but here it is.
This solves issue #84.

### CODE REVIEW

**Comment by fsteggink** [comment]
I'ved fixed the ModuleNotFound erros. I've also updated the pipelines in the config file, since the OGR Memory driver doesn't support any layer creation options at all. I've checked this with GDAL/OGR version 2.4.4 locally.

The proper working of this test can be checked by executing ogrinfo -ro -al -so on the generated geopackages (test1.gpkg and test2.gpkg). Only in the second geopackage have all the geometry fields the name 'geomtest', whereas in the first geopacakge only the layer Gemeenten have this geometry field name. The layers Landsgrens and Provincies both have the default geometry field name 'geom'.

**Comment by fsteggink** [comment]
Next one is done. ✔️

**Comment by justb4** [comment]
@fsteggink Ok, maybe first merge #102 and then merge into your branch?  And then #96. Added you as reviewer and committer to repo. Think we then have progressed some behind versions. If all stable I can bring out Stetl 2.1 also for Docker Image.

**Comment by justb4** [comment]
Maybe better (merging) the other way around: I'll merge this PR first and then merge `origin/master` into PR #102, test etc.

**Pull request merged**
