### PR TITLE
Vsizip filter, fixes #85

### LINKED ISSUE #85: Add new vsizip filter
When importing data from a ZIP file, for example the dutch dataset Bestuurlijke Grenzen, which is a ZIP file containing GML files, the current approach is to use a ZipFileInput in combination with a ZipFileExtractor. The latter extracts the ZIP file to a temporary directory. However, GDAL/OGR also has support for ["virtual file systems"](https://www.gdal.org/gdal_virtual_file_systems.html). One of them is a filter named vsizip. When the string "/vsizip/" is prepended to the input path, OGR can directly read data from a ZIP file without unzipping. When a dataset is large (for example the dutch BGT) and you have not that much disk space left, then this way you don'tneed to unzip the individual files (even albeit the unzipping can be done one by one).

For this reason I've added a new filter named VsiZipFilter, and an abstract base class called VsiFilter, so other virtual file system filters can eventually be added in the future (for example vsicurl). These filters can even be chained, which is also true for their Stetl counterparts.

I will submit a PR when the Python 3 migration is done.

One note though: I've manually disabled the creation of GFS files when importing GML files through a VSI filter. The current approach, which is generating a GFS file next to the GML file (when it is unzipped), should be redesigned. There was an issue that the provided GFS template is ignored. This should be solved. Perhaps by passing GML_GFS_TEMPLATE in a different way (either as -lco, -config, -oo), or make a copy with a newer timestamp as the GML file (which is why the current approach works) and pass the name by GML_GFS_TEMPLATE, instead of generating it in the same location as the (unzipped) GML file.

### PR DESCRIPTION
**Pull request by fsteggink**
For some reason I've never sent a PR for this and other fixes, but here it is.
This solves issue #85.

### CODE REVIEW

**Comment by justb4** [comment]
Quick scan: IMO two causes for build failures (with simple fixes):

* Python 3.4 and 3.5 fail during `lxml` install. My suggestion: we drop Python 3.4 and 3.5 support in `.travis`. Also the Dockerfile uses 3.6. @borrob ?
* module not found errors: as I recall we changed module import naming during Py2->Py3 migration, so all modules should start with `stetl.` e.g. `stetl.inputs.fileinput` etc.

Maybe this also fixes the other PRs....

**Comment by fsteggink** [comment]
I'll check the module not found error. This is my fault.
Regarding Python 3.4/3.5: 3.4 is already EOL, and 3.5 will reach EOL [within 2 months](https://www.python.org/downloads/).

**Comment by borrob** [comment]
With respect to the python version: this is indeed caused by lxml. In the `requirements-main.txt` we specify a version `>=3.7`: https://github.com/geopython/stetl/blob/efe256480c6502537312e9a7ab0d50ee8dccc9bf/requirements-main.txt#L3
The best match is lxml 4.5.2: https://travis-ci.org/github/geopython/stetl/jobs/709917123#L3149 which requires python 3.5 or later.

The error for the build on python 3.5 seems to be caused by markup safe: https://travis-ci.org/github/geopython/stetl/jobs/709917124#L3187
But I haven't investigated what the cause of that error is.

Easy solution would be to drop python 3.4 (and 3.5). I guess that would also mean dropping support on debian jesse and stretch? https://wiki.debian.org/Python Alternatively, we can try and pin the lxml version to the last version supporting python 3.4.

**Comment by fsteggink** [comment]
Regarding the things which should be fixed, maybe it's better to start from PR #94, then #95 and finally this PR. Although I've made three different branches, they are all based on each other. In hindsight it might have been better to make three independent branches, and use a (private) branch with all these fixes merged.

**Comment by justb4** [comment]
It looks good to go, check fail is Python 3.4, 3.5. I'll merge and merge into #102.

**Comment by fsteggink** [comment]
Thank you @justb4 👍

**Pull request merged**
